[theme]
base="light"
primaryColor="#4f46e5"          # Vibrant Indigo
backgroundColor="#ffffff"       # Clean White
secondaryBackgroundColor="#f0f4ff"  # Soft Indigo Tint
textColor="#1e293b"             # Slate Gray for readability
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
